### ISSUE TITLE
option to write report to docx or latex

### ISSUE THREAD

**Issue by peterhalpin** [knickodem/WBdif#46]
Please add an arg for the knit type in summary_report and dif_report

**Comment by knickodem** [comment]
Functionality added with report.format argument. Successful tests with docx and powerpoint, but get an error with pdf
![image](https://user-images.githubusercontent.com/5446480/108276360-b1868f80-7145-11eb-8448-7fee92ad81de.png)

I think this has more to do with my own computer though. Are you able to generate a pdf @peterhalpin ?

**Comment by knickodem** [comment]
Yup, it was just my machine. After updating the necessary latex packages/engine, the function produces pdf reports.
