### ISSUE TITLE
suggested edits to dif_report

### ISSUE THREAD

**Issue by peterhalpin** [knickodem/WBdif#47]
I am having a hard time understanding what is going on with this function because it seems that none of the args are required.  

-Required args should not have defaults (NULL or otherwise) and the function should break when those args are not supplied. No special message is required because if a required argument is missing, R's default error message says so. By convention, arguments without defaults should come first in the arg list. 

- Optional arguments should have defaults (NULL or otherwise). The function should be able to run if the defaults are not changed, which is what makes the argument optional. In dif_report, it seem that this is not possible.

- It seems that the user can get themselves into trouble by having the wrong combination of dif.analysis, dif.models, and effect.robustness for the chosen report.type. Would it be simpler to have different functions for the different report types, rather than one report function that tries to hand all three reports? 

- It is conventional that functions that write to disk require a file name and do not provide a default for this. That way the user has to know where it went.  

- Why does the dif_report require bias.method as a separate argument? biased.items are passed forward by dif.models. If the user enters something for bias.method other than what is saved in dif.models$biased.items, what does dif_report do?

**Comment by knickodem** [comment]
- Let's split dif_report into three functions. dif_report() runs the dif only report, effects_report() is the effects only report, and dif_effects_report() includes both the dif and effects information. That should clarify the required arguments issue. I'm open to other names for the functions of course.
- file.name will no longer have a default
- dif.models$biased.items is always returned as the vector of column indices for biased items. bias.method pulls information from dif.analysis. Primarily the dif.type and (if uniform dif) the item level information to determine direction of dif.

**Comment by knickodem** [comment]
There is now a separate function for each type of report:

- dif_report() requires dif.analysis and only reports DIF information
- effect_report() requires dif.models and effect.robustness and only reports treatment effect robustness checks
- dif_effect_report() requires all three and reports DIF and effects.

bias.method has been replaced. dif_report() and dif_effect_report() use the argument `biased.items` with a character string to retrieve dif information from dif.analysis. Text was added to the output of dif_effect_report() to clarify for which items potential bias was adjusted for in the treatment effect estimates given that dif.models could have had a different user-specified set of items than what is extracted from dif.analysis via the `biased.items` argument.
